Project Management System/Models/ErrorViewModel.cs
namespace Project_Management_System.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project Management System/Models/ProjectModel.cs
using System.Collections.Generic;

namespace Project_Management_System.Models
{
    public class ProjectModel
    {
        public ProjectModel() {
            tasks = new List<TaskModel>();
        }

        public List<TaskModel> tasks { get; set; }

        public int ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectOwner { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Tags { get; set; }
        public string ProjectDescription { get; set; }

        //public List<TaskViewModel> Tasks { get; set; }
    }
}

Project Management System/Models/ProjectViewModel.cs
using System.Collections.Generic;

namespace Project_Management_System.Models
{
    public class ProjectViewModel
    {
        private List<TaskViewModel> tasks;

        public int ProjectId { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectOwner { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Tags { get; set; }
        public string ProjectDescription { get; set; }

        public List<TaskViewModel> Tasks { get; set; }
    }
}

Project Management System/Models/TaskModel.cs
namespace Project_Management_System.Models
{
    public class TaskModel
    {
        public enum TaskPriority
        {
            None,
            Low,
            Medium,
            High
        }
        public TaskModel(int projectId)
        {
            this.ProjectId = projectId;
        }

        public TaskModel()
        {

        }

        public int ProjectId { get; set; }
        public string TaskName { get; set; }
        public string TaskOwner { get; set; }

        public string TaskStatus { get; set; }
        public TimeSpan TaskDuration { get; set; }

        public string TaskDescription { get; set; }
        public DateTime TaskStartDate { get; set; }
        public DateTime TaskEndDate { get; set; }

        public string Tags { get; set; }

        public TaskPriority Priority { get; set; }
        public IFormFile TaskAttachment { get; set; }

    }
}

Project Management System/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Project_Management_System.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project Management System/Controllers/MyTasksController.cs
using Microsoft.AspNetCore.Mvc;

namespace Project_Management_System.Controllers
{
    public class MyTasksController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project Management System/Controllers/NotificationsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Project_Management_System.Controllers
{
    public class NotificationsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project Management System/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Project_Management_System.Models;
using System.Threading.Tasks;

namespace Project_Management_System.Controllers
{
    public class ProjectsController : Controller
    {
        // Create a static list to store project data
        private static List<ProjectModel> projectList = new List<ProjectModel>();
        private static List<TaskModel> taskList = new List<TaskModel>();
        private static int indexIncrement = 1;
        public IActionResult Index()
        {
            return View(projectList);
        }

        [HttpPost]
        public IActionResult AddTask(TaskModel task, int projectId)
        {
            var currentProject = projectList.FirstOrDefault(p => p.ProjectId == projectId);
            Console.WriteLine(task.TaskName);
            Console.WriteLine("-----------");
            return View("ProjectDetails/Tasks");
        }

        public IActionResult ProjectDetails(int id, string page)
        {
            ProjectModel currentProject = projectList.FirstOrDefault(p => p.ProjectId == id);
            if (currentProject == null)
            {
                return RedirectToAction("Index");
            }
            string ViewName = $"ProjectDetails/{page}";
            Console.WriteLine(ViewName);
            Console.WriteLine(currentProject.ProjectId);
            return View(ViewName, currentProject);
        }

        [HttpPost]
        public IActionResult CreateProject(ProjectModel model)
        {
            model.ProjectId = indexIncrement;
            indexIncrement++;
            TaskModel task = new TaskModel(model.ProjectId);
            model.tasks.Add(task);
            //Console.WriteLine(String.Format("Task Name {0}, Task Id {1}", model.tasks[0].TaskName, model.tasks[0].ProjectId));
            projectList.Add(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult Overview_GetCountries(string search)
        {
            List<SelectListItem> countries = GetData(search);

            return Json(countries);
        }

        private static List<SelectListItem> GetData(string search)
        {
            List<SelectListItem> allCountries = new List<SelectListItem>()
            {
                new SelectListItem{ Value = "Sabarivelan", Text = "Sabarivelan"},
                new SelectListItem{ Value = "Ronaldo", Text = "Ronaldo"},
                new SelectListItem{ Value = "Lebron", Text = "Lebron"},
                new SelectListItem{ Value = "Dhoni", Text = "Dhoni"},
            };

            // Filter the items based on the search substring
            List<SelectListItem> filteredCountries = allCountries
                .Where(item => item.Text.Contains(search, StringComparison.OrdinalIgnoreCase))
                .ToList();

            return filteredCountries;
        }
    }
}

Project Management System/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Project_Management_System.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project Management System/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<h1>This is Home Page</h1>

Project Management System/Views/MyTasks/Index.cshtml
@{
    ViewData["Title"] = "My Tasks";
}
<h1>This is My Tasks Page</h1>

Project Management System/Views/Notifications/Index.cshtml
@{
    ViewData["Title"] = "Notifications";
}
<h1>This is Notifications Page</h1>

Project Management System/Views/Projects/Index.cshtml
@model List<Project_Management_System.Models.ProjectModel>
@{
    ViewData["Title"] = "Projects List";
}

<div class="container">
    <div class="d-flex justify-content-between align-items-center py-3">
        <div class="navbar">Projects</div>
        <div class="d-flex">
            <div class="mr-3">
                <input class="form-control" type="search" placeholder="Search">
            </div>
            <button class="btn btn-primary" style="margin-left: 15px;" type="button" onclick="openModal()">+ Add Project</button>
        </div>
    </div>
</div>

<div id="myModal" class="modal">
    <div class="backdrop"></div>
    <div class="modal-content">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center py-3">
                <h3 class="modal-title" style="color: black;">New Project</h3>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <span class="close" style="color: black; cursor: pointer;" onclick="closeModal()">&times;</span>
                    </div>
                </div>
            </div>
            <form asp-controller="Projects" asp-action="CreateProject" method="post">
                <div class="form-group mb-4">
                    <label for="projectTitle">Project Title</label>
                    <input type="text" class="form-control" id="projectTitle" name="ProjectTitle" placeholder="Project Title" required>
                </div>
                <!--needs to fix autocomplete-->
                <div class="form-group mb-4">
                    <label class="mb-2" for="projectOwner">Project Owner</label>
                    <input type="text" id="projectOwner" name="ProjectOwner" class="form-control" autocomplete="off" placeholder="Assign Owner" required>
                    <ul id="itemList" class="list-group mt-2"></ul>
                </div>

                <div class="form-group mb-4">
                    <div class="row">
                        <div class="col-md-6">
                            <label class="mb-2"  for="startTime">Start Time</label>
                            <input type="datetime-local" name="StartTime" class="form-control" id="startTime">
                        </div>
                        <div class="col-md-6">
                            <label class="mb-2" for="endTime">End Time</label>
                            <input type="datetime-local" name="EndTime" class="form-control" id="endTime">
                        </div>
                    </div>
                </div>
                <!-- Bugs in Text area needs to fix-->
                <div class="form-group mb-4">
                    <label class="mb-2" for="projectDescription">Project Description</label>
                    <div>
                        <textarea id="projectDescription" name="ProjectDescription" class="task-description"></textarea>
                    </div>
                </div>

                <div class="form-group mb-4">
                    <label class="mb-2" for="tags">Tags</label>
                    <input type="text" name="Tags" class="form-control" id="tags" placeholder="Enter tags">
                </div>

                <button type="submit" class="btn btn-primary">Create Project</button>
            </form>
        </div>
    </div>
</div>

<div class="container mt-4">
    <table class="table projectlist-table">
        <thead class="projectlist-head">
            <tr>
                <th scope="col">Project</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Tags</th>
                <th scope="col">Owner</th>
            </tr>
        </thead>
        <tbody class="projectlist-body">
            @foreach (var project in Model)
            {
                <tr style="border: solid #fff" onclick="location.href='@Url.Action("ProjectDetails", "Projects", new { id = project.ProjectId, page = "Tasks" })';" style="cursor:pointer;">
                <td>@project.ProjectTitle</td>
                    <td>@project.StartTime</td>
                    <td>@project.EndTime</td>
                    <td>@project.Tags</td>
                    <td>@project.ProjectOwner</td>
                </tr>
            }
        </tbody>
    </table>
</div>



<style>
    table.projectlist-table .projectlist-head tr {
        border-bottom: 3px solid #eee;
        margin-bottom: 5px;
    }
        table.projectlist-table .projectlist-body tr:hover {
        background-color: #eee;
        cursor: pointer;
    }
    .backdrop {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: none; /* Initially hide the backdrop */
    }
    .modal {
        display: block;
        position: fixed;
        top: 0;
        left: 100%;
        width: 50%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        transition: transform 4s ease;
    }


    .modal-content {
        background-color: #fefefe;
        padding: 20px;
        height: 100%;
        border: 0px;
        overflow: auto;
    }

    .task-description {
        width: 100%;
        height: 100px;
        border: 1px solid #ced4da;
        outline-color: #ced4da;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }
    .form-group label {
        font-weight: bold;
    }
</style>

<script>


    function autocomplete(inp, url) {
        var currentFocus;

        inp.addEventListener("input", function (e) {
            var a, b, i, val = this.value;
            closeAllLists();
            if (!val) { return false; }
            currentFocus = -1;
            a = document.createElement("DIV");
            a.setAttribute("id", this.id + "autocomplete-list");
            a.setAttribute("class", "autocomplete-items");
            this.parentNode.appendChild(a);

            // Make an asynchronous request to the server to get the data
            console.log(url + '?search=' + val);
            fetch(url + '?search=' + val)
                .then(response => response.json())
                .then(data => {
                    for (i = 0; i < data.length; i++) {
                        b = document.createElement("DIV");
                        b.innerHTML = data[i].text;
                        b.innerHTML += "<input type='hidden' value='" + data[i].value + "'>";
                        b.addEventListener("click", function (e) {
                            inp.value = this.getElementsByTagName("input")[0].value;
                            closeAllLists();
                        });
                        a.appendChild(b);
                    }
                });
        });

        inp.addEventListener("keydown", function (e) {
            var x = document.getElementById(this.id + "autocomplete-list");
            if (x) x = x.getElementsByTagName("div");
            if (e.keyCode == 40) {
                currentFocus++;
                addActive(x);
            } else if (e.keyCode == 38) {
                currentFocus--;
                addActive(x);
            } else if (e.keyCode == 13) {
                e.preventDefault();
                if (currentFocus > -1) {
                    if (x) x[currentFocus].click();
                }
            }
        });

        function addActive(x) {
            if (!x || !x[currentFocus]) return false;

            removeActive(x);

            if (currentFocus >= x.length) currentFocus = 0;
            if (currentFocus < 0) currentFocus = (x.length - 1);

            x[currentFocus].classList.add("autocomplete-active");
        }

        function removeActive(x) {
            if (!x) return;

            for (var i = 0; i < x.length; i++) {
                if (x[i] && x[i].classList) {
                    x[i].classList.remove("autocomplete-active");
                }
            }
        }

        function closeAllLists(elmnt) {
            var x = document.getElementsByClassName("autocomplete-items");
            for (var i = 0; i < x.length; i++) {
                if (elmnt != x[i] && elmnt != inp) {
                    x[i].parentNode.removeChild(x[i]);
                }
            }
        }

        document.addEventListener("click", function (e) {
            closeAllLists(e.target);
        });
    }

    // Use the URL of your Overview_GetCountries action method
    var countriesUrl = "/Projects/Overview_GetCountries";
    autocomplete(document.getElementById("projectOwner"), countriesUrl);


    // Add this script at the end of your HTML body or in a script tag
    function openModal() {
        const data = @Json.Serialize(Model);
        const body = document.getElementsByTagName("body")[0];
        const myModal = document.getElementById("myModal");
        const backdrop = myModal.querySelector(".backdrop");

        myModal.style.left = "50%";
        myModal.style.display = "block";
        backdrop.style.display = "block"; // Show the backdrop
        body.classList.add("modal-open");
    }

    function closeModal() {
        const body = document.getElementsByTagName("body")[0];
        const myModal = document.getElementById("myModal");
        const backdrop = myModal.querySelector(".backdrop");

        myModal.style.left = "100%";
        myModal.style.display = "none";
        backdrop.style.display = "none"; // Hide the backdrop
        body.classList.remove("modal-open");
    }
</script>

Project Management System/Views/Projects/ProjectDetails.cshtml
@{
    ViewData["Title"] = "Project-Details";
}
<div class="container-fluid">
    <nav class="nav pt-4 pb-0" style="border-bottom: 0.5px solid #CCE;">
        <div class="nav-item  p-2 me-3">Dashboard</div>
        <div class="nav-item active p-2 me-3">Tasks</div>
        <div class="nav-item p-2">Reports</div>
    </nav>
    <div class="d-flex justify-content-end mt-3">
        <button class="btn btn-primary">Add Task</button>
    </div>
    <div class="container mt-4">
        <table class="table projectlist-table">
            <thead class="projectlist-head">
                <tr>
                    <th scope="col">Project</th>
                    <th scope="col">Owner</th>
                    <th scope="col">status</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Priority</th>
                    <th scope="col">CreatedBy</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Tags</th>
                </tr>
            </thead>
            <!--Needs to add task details from the server-->
            <tbody class="projectlist-body">
                <tr style="border: solid #fff; cursor:pointer">
                    <td>Task</td>
                    <td>ProjectOwner</td>
                    <td>Status</td>
                    <td>Duration</td>
                    <td>Priority</td>
                    <td>CreatedBy</td>
                    <td>StartTime</td>
                    <td>EndTime</td>
                    <td>Tags</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<style>
    .nav-item.active {
        border-bottom: 3px solid #02054D !important;
        border-radius: 2px;
        color: #02054D !important;
        font-weight: bold;
    }

    table.projectlist-table .projectlist-head tr {
        border-bottom: 3px solid #eee;
        margin-bottom: 5px;
    }

    table.projectlist-table .projectlist-body tr:hover {
        background-color: #eee;
        cursor: pointer;
    }
</style>

Project Management System/Views/Projects/ProjectDetails/Reports.cshtml
@model Project_Management_System.Models.ProjectModel;
@{
    ViewData["Title"] = "Project-Details";
}
<div class="container-fluid">
    <!--
    <nav class="nav pt-4 pb-0" style="border-bottom: 0.5px solid #CCE;">
        <div class="nav-item p-2 me-3">Dashboard</div>
        <div class="nav-item active p-2 me-3">Tasks @Model.tasks.Count</div>
        <div class="nav-item p-2">Reports</div>
    </nav>
    -->
    <nav class="nav pt-4 pb-0" style="border-bottom: 0.5px solid #CCE;">
        <div class="nav-item p-2 me-3"><a class="project-details nav-link" href="@Url.Action("ProjectDetails", "Projects", new { id = 1, page = "Dashboard" })">Dashboard</a></div>
        <div class="nav-item p-2 me-3"><a class="project-details nav-link" href="@Url.Action("ProjectDetails", "Projects", new { id = 1, page = "Tasks" })">Tasks</a></div>
        <div class="nav-item active p-2"><a class="project-details nav-link" href="@Url.Action("ProjectDetails", "Projects", new { id = 1, page = "Reports" })">Reports</a></div>
    </nav>
</div>
<style>
    .nav-item.active {
        border-bottom: 3px solid #02054D !important;
        border-radius: 2px;
        color: #02054D !important;
        font-weight: bold;
    }

    .project-details.nav-link {
        color: #02054D !important;
        padding: 0px;
    }
    table.projectlist-table .projectlist-head tr {
        border-bottom: 3px solid #eee;
        margin-bottom: 5px;
    }

    table.projectlist-table .projectlist-body tr:hover {
        background-color: #eee;
        cursor: pointer;
    }
</style>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        console.log(@Json.Serialize(Model));
    })
</script>

Project Management System/Views/Projects/ProjectDetails/dashboard.cshtml
@model Project_Management_System.Models.ProjectModel;
@{
    ViewData["Title"] = "Project-Details";
}
<div class="container-fluid">
    <!--
    <nav class="nav pt-4 pb-0" style="border-bottom: 0.5px solid #CCE;">
        <div class="nav-item p-2 me-3">Dashboard</div>
        <div class="nav-item active p-2 me-3">Tasks @Model.tasks.Count</div>
        <div class="nav-item p-2">Reports</div>
    </nav>
    -->
    <nav class="nav pt-4 pb-0" style="border-bottom: 0.5px solid #CCE;">
        <div class="nav-item active p-2 me-3"><a class="project-details nav-link" href="@Url.Action("ProjectDetails", "Projects", new { id = 1, page = "Dashboard" })">Dashboard</a></div>
        <div class="nav-item p-2 me-3"><a class="project-details nav-link" href="@Url.Action("ProjectDetails", "Projects", new { id = 1, page = "Tasks" })">Tasks</a></div>
        <div class="nav-item p-2"><a class="project-details nav-link" href="@Url.Action("ProjectDetails", "Projects", new { id = 1, page = "Reports" })">Reports</a></div>
    </nav>
</div>
<style>
    .nav-item.active {
        border-bottom: 3px solid #02054D !important;
        border-radius: 2px;
        color: #02054D !important;
        font-weight: bold;
    }

    .project-details.nav-link {
        color: #02054D !important;
        padding: 0px;
    }

    table.projectlist-table .projectlist-head tr {
        border-bottom: 3px solid #eee;
        margin-bottom: 5px;
    }

    table.projectlist-table .projectlist-body tr:hover {
        background-color: #eee;
        cursor: pointer;
    }

</style>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        console.log(@Json.Serialize(Model));
    })
</script>

Project Management System/Views/Settings/Index.cshtml
@{
    ViewData["Title"] = "Settings";
}
<h1>This is Settings Page</h1>

Project Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Management_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/project.css" />
    <script src="https://cdn.tiny.cloud/1/0xy33lkz2u2ubt0oq3825img7mu62xvfdf1w0n5tlj0pkw9p/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body class="main-body">

    <header>
        <!-- Sidebar -->
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-primary">
            <div class="position-sticky">
                <div class="list-group list-group-flush mx-3 mt-3">
                    <a href="@Url.Action("Index", "Home")"
                       class="list-group-item list-group-item-action py-2 ripple @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Home</span>
                    </a>
                    <a href="@Url.Action("Index", "Projects")" class="list-group-item list-group-item-action py-2 ripple @(ViewContext.RouteData.Values["Controller"].ToString() == "Projects" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Projects</span>
                    </a>
                    <a href="@Url.Action("Index", "MyTasks")"
                       class="list-group-item list-group-item-action py-2 ripple @(ViewContext.RouteData.Values["Controller"].ToString() == "MyTasks" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span">My Tasks</span>
                    </a>
                    <a href="@Url.Action("Index", "Notifications")" class="list-group-item list-group-item-action py-2 ripple @(ViewContext.RouteData.Values["Controller"].ToString() == "Notifications" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="fas fa-chart-area fa-fw me-3"></i><span>Discuss</span>
                    </a>
                    <a href="@Url.Action("Index", "Settings")"
                       class="list-group-item list-group-item-action py-2 ripple @(ViewContext.RouteData.Values["Controller"].ToString() == "Settings" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Settings</span>
                    </a>
                </div>
            </div>
        </nav>
        <!-- Sidebar -->
        <!-- Navbar -->
        <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #F1F0F0;">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Toggle button -->
                <button class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#sidebarMenu"
                        aria-controls="sidebarMenu"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>


                <!-- Brand -->
                <a class="navbar-brand" href="#">
                    <h3>Greetsoft</h3>
                </a>

                <!-- Right links -->
                <ul class="navbar-nav ms-auto d-flex flex-row">
                    <!-- Notification dropdown -->
                    <li class="nav-item dropdown">  
                        <button type="button" class="btn btn-sm mt-1 position-relative" style="background-color: #EAE6E6; border-radius: 50%;">
                            <img src="/images/bell.png" style="width: 22px; height: 22px; " alt="notification icon">
                        </button>
                    </li>

                    <!-- Icon -->
                    <li class="nav-item">
                        <a class="nav-link me-3 me-lg-0" href="#">
                            <i class="fas fa-fill-drip"></i>
                        </a>
                    </li>

                    <!-- Avatar -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
                           href="#"
                           id="navbarDropdownMenuLink"
                           role="button"
                           data-mdb-toggle="dropdown"
                           aria-expanded="false">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp"
                                 class="rounded-circle"
                                 height="22"
                                 alt="Avatar"
                                 loading="lazy" />
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="#">My profile</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Settings</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->
    <!--Main layout-->
    <main style="margin-top: 58px;  ">
        <div class="container">
            @RenderBody()
        </div>
    </main>
    <!--Main layout-->

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>